<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Rooms_sample extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 1","HSB - 1","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 2","HSB - 2","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 3","HSB - 3","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 4","HSB - 4","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 5","HSB - 5","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 6","HSB - 6","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 7","HSB - 7","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 8","HSB - 8","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 9","HSB - 9","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 10","HSB - 10","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 11","HSB - 11","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 12","HSB - 12","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 13","HSB - 13","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 14","HSB - 14","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 15","HSB - 15","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 16","HSB - 16","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 17","HSB - 17","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 18","HSB - 18","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"HIGH SCHOOL BUILDING","HSB BLDG","HSB - 19","HSB - 19","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"CAIS / CSWD","CAIS / CSWD","CAIS - 21","CAIS - 21","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"CAIS / CSWD","CAIS / CSWD","CAIS - 22","CAIS - 22","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"CAIS / CSWD","CAIS / CSWD","CAIS - 23","CAIS - 23","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"CAIS / CSWD","CAIS / CSWD","CAIS - 24","CAIS - 24","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"CAIS / CSWD","CAIS / CSWD","CSWD - 201","CSWD - 201","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"CAIS / CSWD","CAIS / CSWD","CSWD - 202","CSWD - 202","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"CSM BUILDING","CSM BLDG","CSM - 11","CSM - 11","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"CSM BUILDING","CSM BLDG","CSM - 12","CSM - 12","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF TEADER EDUCATION","CTE BLDG","CTE - 14","CTE - 14","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF TEADER EDUCATION","CTE BLDG","CTE - 21","CTE - 21","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF TEADER EDUCATION","CTE BLDG","CTE - 22","CTE - 22","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF TEADER EDUCATION","CTE BLDG","CTE - 23","CTE - 23","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF TEADER EDUCATION","CTE BLDG","CTE - 24","CTE - 24","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF TEADER EDUCATION","CTE BLDG","CTE - 25","CTE - 25","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF TEADER EDUCATION","CTE BLDG","CTE - 26","CTE - 26","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF TEADER EDUCATION","CTE BLDG","CTE - 27","CTE - 27","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF TEADER EDUCATION","CTE BLDG","CTE - 28","CTE - 28","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF TEADER EDUCATION","CTE BLDG","CTE - 29","CTE - 29","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF ENGINEERING ","COE BLDG","COE - 111","COE - 111","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF ENGINEERING ","COE BLDG","COE - 112","COE - 112","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF ENGINEERING ","COE BLDG","COE - 120","COE - 120","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF ENGINEERING ","COE BLDG","COE - 206","COE - 206","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF ENGINEERING ","COE BLDG","COE - 207","COE - 207","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF ENGINEERING ","COE BLDG","COE - 211","COE - 211","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF ENGINEERING ","COE BLDG","COE - 212","COE - 212","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF ENGINEERING ","COE BLDG","COE - 214","COE - 214","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF ENGINEERING ","COE BLDG","COE - 215","COE - 215","30",NULL,"",NOW(),NOW());');
        DB::statement('INSERT INTO school_rooms(school_room_id,school_room_isactive,school_room_bldg_name,school_room_bldg_abr,school_room_name,school_room_number,school_room_max_capacity,school_room_proctor_user_id,school_room_description,date_created,date_updated) VALUES(NULL,1,"COLLEGE  OF ENGINEERING ","COE BLDG","COE - 216","COE - 216","30",NULL,"",NOW(),NOW());');


    }
}
